apiVersion: v1
kind: Pod
metadata:
  name: target-evictor
  namespace: bad-tenant
spec:
  containers:
  - name: target-evictor
    image: nginxdemos/hello
    resources:
      requests:
        cpu: 1
        memory: 128Mi
      limits:
        cpu: 1
        memory: 128Mi
  priorityClassName: high-priority
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:  # avoid LimitPodHardAntiAffinityTopology admision controller and use kubernetes.io/hostname topologyKey
      - weight: 100
        podAffinityTerm:
          namespaces:
          - default
          labelSelector:
            matchExpressions:
            - key: target
              operator: In
              values:
              - me
          topologyKey: kubernetes.io/hostname # neutral node label (targeting all nodes, in case we don't know nodes labels)


### IF CPU supply is close to be exhausted => schedule process => eviction
