apiVersion: v1
kind: Pod
metadata:
  name: scout
  namespace: bad-tenant
  labels:
    app: scout
spec:
  containers:
  - name: scout
    image: nginxdemos/hello
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 1
        memory: 128Mi
      limits:
        cpu: 1
        memory: 128Mi
  priorityClassName: high-priority
  nodeName: minikube-m02
 
